
name: BuildBin

on:
  push:
    branches: [ master ]

jobs:
  buildWinBin:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'
    - run: pushd \python
    #- run: ./python/build_bin.sh
    - run: pyinstaller trezorCliTool.spec
