
name: BuildBin

on:
  push:
    branches: [ master ]

jobs:
  buildWinBin:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'
    #- run: ./python/build_bin.sh
    #- run: python setup.py install
    - run: wget -N -c -O  libusb-1.0.23.7z https://github.com/libusb/libusb/releases/download/v1.0.23/libusb-1.0.23.7z
    - run: dir
    - run: 7z e libusb-1.0.23.7z
    - run: dir
    - run: pip install pyinstaller
    - name: Step 2
      working-directory: .\python
      run: pyinstaller trezorCliTool.spec
