
name: BuildBin

on:
  push:
    branches: [ master ]

jobs:
  buildWinBin:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'
    #- run: ./python/build_bin.sh
    - name: Run Tests
        working-directory: .\python
        run: python setup.py install
    - run: pip install pyinstaller
    - run: pyinstaller python/trezorCliTool.spec
