
name: BuildBin

on:
  push:
    branches: [ master ]

jobs:
  buildWinBin:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'
    #- run: ./python/build_bin.sh
    - name: Run Tests
      working-directory: .\python
      run: python setup.py install
    - name: Step 1
      working-directory: .\python
      run: vcpkg install libusb
    - run: pip install pyinstaller
    - name: Step 2
      working-directory: .\python
      run: pyinstaller trezorCliTool.spec
