
name: BuildBin

on:
  push:
    branches: [ master ]

jobs:
  buildWinBin:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'
    #- run: ./python/build_bin.sh
    - name: Run Tests
      working-directory: .\python
      run: python setup.py install
      run: curl https://github.com/libusb/libusb/releases/download/v1.0.23/libusb-1.0.23.tar.bz2 --output libusb-1.0.23.tar.bz2
      run: tar xf libusb.tar.bz2
    - run: pip install pyinstaller
    - name: Step 2
      working-directory: .\python
      run: pyinstaller trezorCliTool.spec
